# Generated by Django 6.0.6 on 2026-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appeals/'),
        ),
    ]
