# Generated by Django 6.0.6 on 2026-06-20 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_appeal_image'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={},
        ),
        migrations.AddField(
            model_name='appeal',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='priority',
            field=models.CharField(choices=[('normal', 'Oddiy'), ('medium', 'Zarur'), ('urgent', 'Shoshilinch')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
